/*
 * Copyright (c) PyPTO Contributors.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * -----------------------------------------------------------------------------------------------------------
 */

// Kernel Function: expert_down_aiv
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#if !defined(__CPU_SIM)
#include "intrinsic.h"

// A2A3 mixed tasks run the same AIV kernel on two vector cores.
// Bridge the runtime-provided lane id into PTO-ISA get_subblockid().
[[block_local]] static int32_t pypto_runtime_subblock_id;
#define get_subblockid() pypto_runtime_subblock_id
#endif

#include <pto/pto-inst.hpp>
#include "runtime_tensor_compat.hpp"
#include "intrinsic.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
  dcci((__gm__ void*)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void expert_down_aic(__gm__ int32_t* v1, __gm__ bfloat16_t* v2, __gm__ int32_t* v3, __gm__ int8_t* v4, __gm__ int8_t* v5, __gm__ float* v6, __gm__ float* v7, __gm__ float* v8, __gm__ float* v9, int64_t v10, int32_t v11, int32_t v12) {
  const int64_t v13 = 10;
  const int64_t v14 = 128;
  const int64_t v15 = 15;
  const int64_t v16 = 2;
  const int64_t v17 = 256;
  const int64_t v18 = 16;
  const int64_t v19 = 1280;
  const int64_t v20 = 36;
  const int64_t v21 = 4096;
  const int64_t v22 = 1;
  const int64_t v23 = 0;
  const int64_t v24 = 32768;
  const int32_t v25 = 0;
  using T = float;

  #if defined(__DAV_CUBE__)
  auto v26 = TPipe<0, Direction::DIR_C2V, 16384, 8, 8, true>(v9, v25, v25);
  // pto: %worker_inline519__ssa_v0
  // pto: %t__tile
  int32_t v27 = v1[v22];
  // pto: %1
  int64_t v28 = (int64_t) v27;
  set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
  set_flag(PIPE_FIX, PIPE_M, EVENT_ID0);
  set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID2);
  set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID3);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
  // pto: %2, %active_expert_count_inline574__phi_v9, %4
  for (int64_t i29 = (int64_t) v11; i29 < ((int64_t) ((uint64_t) (v28 > v20 ? v20 : v28) * (uint64_t) v18)); i29 += v10) {
    // pto: %6, %7
    int64_t v30 = (int64_t) ((uint64_t) (i29 % v18) * (uint64_t) v17);
    // pto: %5, %9, %8
    int32_t v31 = v1[(int64_t) ((uint64_t) (i29 / v18) + (uint64_t) v16)];
    // pto: %10
    int64_t v32 = (int64_t) v31;
    // pto: %n_rows_inline541__tile
    int32_t v33 = v3[v32];
    // pto: %11, %12, %13
    for (int64_t j34 = v23; j34 < ((int64_t) ((uint64_t) ((int64_t) v33) + (uint64_t) v15) / v18); j34 += v22) {
      // pto: %14, %16, %15
      int64_t v35 = (int64_t) ((uint64_t) ((int64_t) ((uint64_t) v32 * (uint64_t) v14)) + (uint64_t) ((int64_t) ((uint64_t) j34 * (uint64_t) v18)));
      // pto: %h0_inline558__tile
      Tile<TileType::Mat, int8_t, 16, 128, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v36 = Tile<TileType::Mat, int8_t, 16, 128, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v18, v14);
      // pto: %h0_inline558__tile
      uint64_t v37 = (uint64_t) v24;
      TASSIGN(v36, v37);
      // pto: %h_i8_inline553__rv_v2_pview
      pto::Shape<1, 1, 1, 16, 128> v38 = pto::Shape<1, 1, 1, 16, 128>();
      // pto: %h_i8_inline553__rv_v2_pview
      pto::Stride<20480, 20480, 20480, 1280, 1> v39 = pto::Stride<20480, 20480, 20480, 1280, 1>();
      // pto: %h_i8_inline553__rv_v2_pview
      GlobalTensor<int8_t, pto::Shape<1, 1, 1, 16, 128>, pto::Stride<20480, 20480, 20480, 1280, 1>, pto::Layout::ND> v40 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 16, 128>, pto::Stride<20480, 20480, 20480, 1280, 1>, pto::Layout::ND>(v4 + ((v23 + v35 * v19) + v23 * v22), v38, v39);
      wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
      TLOAD(v36, v40);
      set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
      // pto: %wd0_inline585__tile
      Tile<TileType::Mat, int8_t, 128, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v41 = Tile<TileType::Mat, int8_t, 128, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v14, v17);
      // pto: %wd0_inline585__tile
      uint64_t v42 = (uint64_t) v23;
      TASSIGN(v41, v42);
      // pto: %17
      int64_t v43 = (int64_t) ((uint64_t) v32 * (uint64_t) v19);
      // pto: %w_down_2d_inline571__ssa_v0_pview
      pto::Shape<1, 8, 8, 16, 32> v44 = pto::Shape<1, 8, 8, 16, 32>();
      // pto: %w_down_2d_inline571__ssa_v0_pview
      pto::Stride<327680, 40960, 512, 32, 1> v45 = pto::Stride<327680, 40960, 512, 32, 1>();
      // pto: %w_down_2d_inline571__ssa_v0_pview
      GlobalTensor<int8_t, pto::Shape<1, 8, 8, 16, 32>, pto::Stride<327680, 40960, 512, 32, 1>, pto::Layout::NZ> v46 = GlobalTensor<int8_t, pto::Shape<1, 8, 8, 16, 32>, pto::Stride<327680, 40960, 512, 32, 1>, pto::Layout::NZ>(v5 + v43 * v21 + (v30 / 32) * 40960, v44, v45);
      TLOAD(v41, v46);
      set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID1);
      // pto: %h0_inline558__tile_Left
      Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v47 = Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v18, v14);
      // pto: %h0_inline558__tile_Left
      uint64_t v48 = (uint64_t) v23;
      TASSIGN(v47, v48);
      wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
      TMOV(v47, v36);
      // pto: %wd0_inline585__tile_Right
      Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v49 = Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v14, v17);
      // pto: %wd0_inline585__tile_Right
      uint64_t v50 = (uint64_t) v23;
      TASSIGN(v49, v50);
      wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID1);
      TMOV(v49, v41);
      set_flag(PIPE_MTE1, PIPE_M, EVENT_ID0);
      set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
      // pto: %y_acc_inline517__tile
      Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v51 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v18, v17);
      // pto: %y_acc_inline517__tile
      uint64_t v52 = (uint64_t) v23;
      TASSIGN(v51, v52);
      wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID0);
      wait_flag(PIPE_FIX, PIPE_M, EVENT_ID0);
      TMATMUL(v51, v47, v49);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
      wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
      for (int64_t k53 = v22; k53 < v13; k53 += v22) {
        // pto: %18
        int64_t v54 = (int64_t) ((uint64_t) k53 * (uint64_t) v14);
        // pto: %hk_inline551__tile
        Tile<TileType::Mat, int8_t, 16, 128, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v55 = Tile<TileType::Mat, int8_t, 16, 128, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v18, v14);
        // pto: %hk_inline551__tile
        uint64_t v56 = (uint64_t) v24;
        TASSIGN(v55, v56);
        // pto: %19
        pto::Shape<1, 1, 1, 16, 128> v57 = pto::Shape<1, 1, 1, 16, 128>();
        // pto: %19
        pto::Stride<20480, 20480, 20480, 1280, 1> v58 = pto::Stride<20480, 20480, 20480, 1280, 1>();
        // pto: %19
        GlobalTensor<int8_t, pto::Shape<1, 1, 1, 16, 128>, pto::Stride<20480, 20480, 20480, 1280, 1>, pto::Layout::ND> v59 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 16, 128>, pto::Stride<20480, 20480, 20480, 1280, 1>, pto::Layout::ND>(v4 + ((v23 + v35 * v19) + v54 * v22), v57, v58);
        wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID2);
        TLOAD(v55, v59);
        set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID2);
        // pto: %wdk_inline516__tile
        Tile<TileType::Mat, int8_t, 128, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v60 = Tile<TileType::Mat, int8_t, 128, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v14, v17);
        // pto: %wdk_inline516__tile
        uint64_t v61 = (uint64_t) v23;
        TASSIGN(v60, v61);
        // pto: %22
        pto::Shape<1, 8, 8, 16, 32> v62 = pto::Shape<1, 8, 8, 16, 32>();
        // pto: %22
        pto::Stride<327680, 40960, 512, 32, 1> v63 = pto::Stride<327680, 40960, 512, 32, 1>();
        // pto: %21, %22
        GlobalTensor<int8_t, pto::Shape<1, 8, 8, 16, 32>, pto::Stride<327680, 40960, 512, 32, 1>, pto::Layout::NZ> v64 = GlobalTensor<int8_t, pto::Shape<1, 8, 8, 16, 32>, pto::Stride<327680, 40960, 512, 32, 1>, pto::Layout::NZ>(v5 + v43 * v21 + (v54 / 16) * 512 + (v30 / 32) * 40960, v62, v63);
        wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID3);
        TLOAD(v60, v64);
        set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID3);
        // pto: %hk_inline551__tile_Left
        Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v65 = Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v18, v14);
        // pto: %hk_inline551__tile_Left
        uint64_t v66 = (uint64_t) v23;
        TASSIGN(v65, v66);
        wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID2);
        wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
        TMOV(v65, v55);
        set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID2);
        // pto: %wdk_inline516__tile_Right
        Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v67 = Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v14, v17);
        // pto: %wdk_inline516__tile_Right
        uint64_t v68 = (uint64_t) v23;
        TASSIGN(v67, v68);
        wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID3);
        TMOV(v67, v60);
        set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID3);
        set_flag(PIPE_MTE1, PIPE_M, EVENT_ID1);
        // pto: %0
        Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v69 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v18, v17);
        // pto: %0
        uint64_t v70 = (uint64_t) v23;
        TASSIGN(v69, v70);
        wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID1);
        TMATMUL_ACC(v69, v69, v65, v67);
        set_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
      }
      set_flag(PIPE_M, PIPE_FIX, EVENT_ID0);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
      set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
      wait_flag(PIPE_M, PIPE_FIX, EVENT_ID0);
      TPUSH<TPipe<0, Direction::DIR_C2V, 16384, 8, 8, true>, Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>, TileSplitAxis::TILE_NO_SPLIT>(v26, v51);
      set_flag(PIPE_FIX, PIPE_M, EVENT_ID0);
    }
  }
  wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
  wait_flag(PIPE_FIX, PIPE_M, EVENT_ID0);
  wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID2);
  wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID3);
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
  #endif // __DAV_CUBE__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

static __aicore__ void expert_down_aiv(__gm__ int32_t* v1, __gm__ bfloat16_t* v2, __gm__ int32_t* v3, __gm__ int8_t* v4, __gm__ int8_t* v5, __gm__ float* v6, __gm__ float* v7, __gm__ float* v8, __gm__ float* v9, int64_t v10, int32_t v11, int32_t v12, int32_t v13) {
  RoundMode v14 = RoundMode::CAST_ROUND;
  SaturationMode v15 = SaturationMode::OFF;
  RoundMode v16 = RoundMode::CAST_NONE;
  const int64_t v17 = 128;
  const int64_t v18 = 15;
  const int64_t v19 = 2;
  const int64_t v20 = 256;
  const int64_t v21 = 16;
  const int64_t v22 = 0;
  const int64_t v23 = 36;
  const int64_t v24 = 4096;
  const int64_t v25 = 4608;
  const int64_t v26 = 1;
  const int64_t v27 = 131200;
  const int64_t v28 = 131136;
  const int64_t v29 = 131072;
  const int64_t v30 = 147584;
  const int32_t v31 = 0;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  auto v32 = TPipe<0, Direction::DIR_C2V, 16384, 8, 8, true>(v9, v31, v31);
  // pto: %subblock_idx, %20
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
  if ((int64_t) v13 == v22) {
    // pto: %worker_inline519__ssa_v0
    // pto: %21
    int32_t v33 = v1[v26];
    // pto: %22
    int64_t v34 = (int64_t) v33;
    // pto: %23, %active_expert_count_inline574__phi_v9, %25
    for (int64_t i35 = (int64_t) v11; i35 < ((int64_t) ((uint64_t) (v34 > v23 ? v23 : v34) * (uint64_t) v21)); i35 += v10) {
      // pto: %27, %28
      int64_t v36 = (int64_t) ((uint64_t) (i35 % v21) * (uint64_t) v20);
      // pto: %26, %30, %29
      int32_t v37 = v1[(int64_t) ((uint64_t) (i35 / v21) + (uint64_t) v19)];
      // pto: %31
      int64_t v38 = (int64_t) v37;
      // pto: %n_rows_inline541__tile
      int32_t v39 = v3[v38];
      // pto: %32
      int64_t v40 = (int64_t) v39;
      // pto: %33, %34
      for (int64_t j41 = v22; j41 < ((int64_t) ((uint64_t) v40 + (uint64_t) v18) / v21); j41 += v26) {
        // pto: %36
        int64_t v42 = (int64_t) ((uint64_t) j41 * (uint64_t) v21);
        // pto: %35, %37
        int64_t v43 = (int64_t) ((uint64_t) ((int64_t) ((uint64_t) v38 * (uint64_t) v17)) + (uint64_t) v42);
        // pto: %41
        int64_t v44 = (int64_t) ((uint64_t) v40 - (uint64_t) v42);
        // pto: %42
        int64_t v45 = v44 < v21 ? v44 : v21;
        // pto: %wd_scale_row_inline515__tile
        Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v46 = Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v26, v20);
        // pto: %wd_scale_row_inline515__tile
        uint64_t v47 = (uint64_t) v30;
        TASSIGN(v46, v47);
        // pto: %w_down_r_scale__ssa_v0_pview
        pto::Shape<1, 1, 1, 1, 256> v48 = pto::Shape<1, 1, 1, 1, 256>();
        // pto: %w_down_r_scale__ssa_v0_pview
        pto::Stride<4096, 4096, 4096, 4096, 1> v49 = pto::Stride<4096, 4096, 4096, 4096, 1>();
        // pto: %w_down_r_scale__ssa_v0_pview
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 256>, pto::Stride<4096, 4096, 4096, 4096, 1>, pto::Layout::ND> v50 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 256>, pto::Stride<4096, 4096, 4096, 4096, 1>, pto::Layout::ND>(v6 + ((v22 + v38 * v24) + v36 * v26), v48, v49);
        wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
        TLOAD(v46, v50);
        // pto: %t__tile
        Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v51 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v26, v21);
        // pto: %t__tile
        uint64_t v52 = (uint64_t) v29;
        TASSIGN(v51, v52);
        // pto: %h_scale_dq_all_inline598__rv_v2_pview
        pto::Shape<1, 1, 1, 1, 16> v53 = pto::Shape<1, 1, 1, 1, 16>();
        // pto: %h_scale_dq_all_inline598__rv_v2_pview
        pto::Stride<4608, 4608, 4608, 4608, 1> v54 = pto::Stride<4608, 4608, 4608, 4608, 1>();
        // pto: %h_scale_dq_all_inline598__rv_v2_pview
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, 16>, pto::Stride<4608, 4608, 4608, 4608, 1>, pto::Layout::ND> v55 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 16>, pto::Stride<4608, 4608, 4608, 4608, 1>, pto::Layout::ND>(v7 + ((v22 + v22 * v25) + v43 * v26), v53, v54);
        TLOAD(v51, v55);
        // pto: %0
        Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v56 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v26, v45);
        // pto: %0
        uint64_t v57 = (uint64_t) v28;
        TASSIGN(v56, v57);
        // pto: %local_routed_weight__ssa_v1_pview
        int64_t v58 = v45 * v26;
        // pto: %local_routed_weight__ssa_v1_pview
        pto::Shape<1, 1, 1, 1, -1> v59 = pto::Shape<1, 1, 1, 1, -1>(v45);
        // pto: %local_routed_weight__ssa_v1_pview
        pto::Stride<-1, -1, -1, -1, 1> v60 = pto::Stride<-1, -1, -1, -1, 1>(v58, v58, v58, v58);
        // pto: %local_routed_weight__ssa_v1_pview
        GlobalTensor<float, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, 1>, pto::Layout::ND> v61 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<-1, -1, -1, -1, 1>, pto::Layout::ND>(v8 + (v22 + v43 * v26), v59, v60);
        TLOAD(v56, v61);
        // pto: %y_acc_inline517__rv_v2_Vec
        Tile<TileType::Vec, int32_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v62 = Tile<TileType::Vec, int32_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v21, v20);
        TPOP<TPipe<0, Direction::DIR_C2V, 16384, 8, 8, true>, Tile<TileType::Vec, int32_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>, TileSplitAxis::TILE_NO_SPLIT>(v32, v62);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
        // pto: %1
        Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v63 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v21, v20);
        // pto: %1
        uint64_t v64 = (uint64_t) v27;
        TASSIGN(v63, v64);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
        wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
        TCVT(v63, v62, v16, v15);
        TFREE<TPipe<0, Direction::DIR_C2V, 16384, 8, 8, true>, TileSplitAxis::TILE_NO_SPLIT>(v32);
        // pto: %t__rm_a0_tmp_v0
        Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v65 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v26, v21);
        // pto: %t__rm_a0_tmp_v0
        uint64_t v66 = (uint64_t) v29;
        TASSIGN(v65, v66);
        // pto: %t__rm_a1_tmp_v1
        Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v67 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v26, v21);
        // pto: %t__rm_a1_tmp_v1
        uint64_t v68 = (uint64_t) v28;
        TASSIGN(v67, v68);
        // pto: %t__row_major_tmp_v2
        Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v69 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v26, v21);
        // pto: %t__row_major_tmp_v2
        uint64_t v70 = (uint64_t) v29;
        TASSIGN(v69, v70);
        TMUL(v69, v65, v67);
        // pto: %2
        Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v71 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v21, v26);
        // pto: %2
        uint64_t v72 = (uint64_t) v29;
        TASSIGN(v71, v72);
        // pto: %3
        Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v73 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v21, v20);
        // pto: %3
        uint64_t v74 = (uint64_t) v27;
        TASSIGN(v73, v74);
        pipe_barrier(PIPE_V);
        TROWEXPANDMUL(v73, v63, v71);
        // pto: %y_2d_inline513__tile
        Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v75 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v21, v20);
        // pto: %y_2d_inline513__tile
        uint64_t v76 = (uint64_t) v27;
        TASSIGN(v75, v76);
        pipe_barrier(PIPE_V);
        TCOLEXPANDMUL(v75, v73, v46);
        set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
        v75.SetValidShape(v45, v20);
        // pto: %y_m_inline511__tile
        Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null> v77 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null>(v21, v20);
        // pto: %y_m_inline511__tile
        uint64_t v78 = (uint64_t) v27;
        TASSIGN(v77, v78);
        pipe_barrier(PIPE_V);
        TFILLPAD(v77, v75);
        // pto: %4
        Tile<TileType::Vec, bfloat16_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null> v79 = Tile<TileType::Vec, bfloat16_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null>(v21, v20);
        // pto: %4
        uint64_t v80 = (uint64_t) v27;
        TASSIGN(v79, v80);
        pipe_barrier(PIPE_V);
        TCVT(v79, v77, v14, v15);
        set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
        // pto: %local_routed_y__iter_v3_pview
        pto::Shape<1, 1, 1, 16, 256> v81 = pto::Shape<1, 1, 1, 16, 256>();
        // pto: %local_routed_y__iter_v3_pview
        pto::Stride<65536, 65536, 65536, 4096, 1> v82 = pto::Stride<65536, 65536, 65536, 4096, 1>();
        // pto: %local_routed_y__iter_v3_pview
        GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND> v83 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND>(v2 + ((v22 + v43 * v24) + v36 * v26), v81, v82);
        wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
        TSTORE(v83, v79);
        set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
      }
    }
  } else {
    // pto: %44
    // pto: %45
    int32_t v84 = v1[v26];
    // pto: %46
    int64_t v85 = (int64_t) v84;
    // pto: %47, %48, %50
    for (int64_t i86 = (int64_t) v11; i86 < ((int64_t) ((uint64_t) (v85 > v23 ? v23 : v85) * (uint64_t) v21)); i86 += v10) {
      // pto: %52, %54, %53
      int32_t v87 = v1[(int64_t) ((uint64_t) (i86 / v21) + (uint64_t) v19)];
      // pto: %55, %56
      int32_t v88 = v3[(int64_t) v87];
      // pto: %57, %58, %59
      for (int64_t j89 = v22; j89 < ((int64_t) ((uint64_t) ((int64_t) v88) + (uint64_t) v18) / v21); j89 += v26) {
        // pto: %5
        Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v90 = Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v22, v22);
        // pto: %5
        uint64_t v91 = (uint64_t) v30;
        TASSIGN(v90, v91);
        // pto: %61
        Tile<TileType::Vec, int32_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v92 = Tile<TileType::Vec, int32_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v21, v20);
        v92.SetValidShape(v22, v22);
        wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
        TPOP<TPipe<0, Direction::DIR_C2V, 16384, 8, 8, true>, Tile<TileType::Vec, int32_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>, TileSplitAxis::TILE_NO_SPLIT>(v32, v92);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
        // pto: %10
        Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v93 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v22, v22);
        // pto: %10
        uint64_t v94 = (uint64_t) v27;
        TASSIGN(v93, v94);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
        pipe_barrier(PIPE_V);
        TCVT(v93, v92, v16, v15);
        set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
        TFREE<TPipe<0, Direction::DIR_C2V, 16384, 8, 8, true>, TileSplitAxis::TILE_NO_SPLIT>(v32);
        // pto: %11
        Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v95 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v22, v22);
        // pto: %11
        uint64_t v96 = (uint64_t) v29;
        TASSIGN(v95, v96);
        // pto: %12
        Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v97 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v22, v22);
        // pto: %12
        uint64_t v98 = (uint64_t) v28;
        TASSIGN(v97, v98);
        // pto: %13
        Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v99 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v22, v22);
        // pto: %13
        uint64_t v100 = (uint64_t) v29;
        TASSIGN(v99, v100);
        TMUL(v99, v95, v97);
        // pto: %14
        Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v101 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v22, v22);
        // pto: %14
        uint64_t v102 = (uint64_t) v29;
        TASSIGN(v101, v102);
        // pto: %15
        Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v103 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v22, v22);
        // pto: %15
        uint64_t v104 = (uint64_t) v27;
        TASSIGN(v103, v104);
        pipe_barrier(PIPE_V);
        TROWEXPANDMUL(v103, v93, v101);
        // pto: %16
        Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v105 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v22, v22);
        // pto: %16
        uint64_t v106 = (uint64_t) v27;
        TASSIGN(v105, v106);
        pipe_barrier(PIPE_V);
        TCOLEXPANDMUL(v105, v103, v90);
        v105.SetValidShape(v22, v22);
        // pto: %18
        Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null> v107 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null>(v22, v22);
        // pto: %18
        uint64_t v108 = (uint64_t) v27;
        TASSIGN(v107, v108);
        pipe_barrier(PIPE_V);
        TFILLPAD(v107, v105);
        // pto: %19
        Tile<TileType::Vec, bfloat16_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null> v109 = Tile<TileType::Vec, bfloat16_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null>(v22, v22);
        // pto: %19
        uint64_t v110 = (uint64_t) v27;
        TASSIGN(v109, v110);
        pipe_barrier(PIPE_V);
        TCVT(v109, v107, v14, v15);
      }
    }
  }
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
#if !defined(__CPU_SIM)
    // Read A2A3 mixed-task subblock id from runtime dispatch context
    pypto_runtime_subblock_id = get_sub_block_id(args);
#endif

    // Read logical SPMD block identity from runtime dispatch payload
    int32_t __pypto_spmd_block_idx = get_block_idx(args);
    int32_t __pypto_spmd_block_num = get_block_num(args);

    // Read SPMD subblock (AIV lane) id from runtime dispatch payload
    int32_t __pypto_spmd_subblock_idx = get_sub_block_id(args);

    // Unpack tensor: local_route_count__ssa_v0
    __gm__ PyPTORuntimeTensor* local_route_count__ssa_v0_tensor = reinterpret_cast<__gm__ PyPTORuntimeTensor*>(args[0]);
    __gm__ int32_t* local_route_count__ssa_v0 = reinterpret_cast<__gm__ int32_t*>(local_route_count__ssa_v0_tensor->buffer.addr) + local_route_count__ssa_v0_tensor->start_offset;

    // Unpack tensor: local_routed_y__ssa_v0
    __gm__ PyPTORuntimeTensor* local_routed_y__ssa_v0_tensor = reinterpret_cast<__gm__ PyPTORuntimeTensor*>(args[1]);
    __gm__ bfloat16_t* local_routed_y__ssa_v0 = reinterpret_cast<__gm__ bfloat16_t*>(local_routed_y__ssa_v0_tensor->buffer.addr) + local_routed_y__ssa_v0_tensor->start_offset;

    // Unpack tensor: local_expert_count__ssa_v1
    __gm__ PyPTORuntimeTensor* local_expert_count__ssa_v1_tensor = reinterpret_cast<__gm__ PyPTORuntimeTensor*>(args[2]);
    __gm__ int32_t* local_expert_count__ssa_v1 = reinterpret_cast<__gm__ int32_t*>(local_expert_count__ssa_v1_tensor->buffer.addr) + local_expert_count__ssa_v1_tensor->start_offset;

    // Unpack tensor: h_i8_inline553__rv_v2
    __gm__ PyPTORuntimeTensor* h_i8_inline553__rv_v2_tensor = reinterpret_cast<__gm__ PyPTORuntimeTensor*>(args[3]);
    __gm__ int8_t* h_i8_inline553__rv_v2 = reinterpret_cast<__gm__ int8_t*>(h_i8_inline553__rv_v2_tensor->buffer.addr) + h_i8_inline553__rv_v2_tensor->start_offset;

    // Unpack tensor: w_down_2d_inline571__ssa_v0
    __gm__ PyPTORuntimeTensor* w_down_2d_inline571__ssa_v0_tensor = reinterpret_cast<__gm__ PyPTORuntimeTensor*>(args[4]);
    __gm__ int8_t* w_down_2d_inline571__ssa_v0 = reinterpret_cast<__gm__ int8_t*>(w_down_2d_inline571__ssa_v0_tensor->buffer.addr) + w_down_2d_inline571__ssa_v0_tensor->start_offset;

    // Unpack tensor: w_down_r_scale__ssa_v0
    __gm__ PyPTORuntimeTensor* w_down_r_scale__ssa_v0_tensor = reinterpret_cast<__gm__ PyPTORuntimeTensor*>(args[5]);
    __gm__ float* w_down_r_scale__ssa_v0 = reinterpret_cast<__gm__ float*>(w_down_r_scale__ssa_v0_tensor->buffer.addr) + w_down_r_scale__ssa_v0_tensor->start_offset;

    // Unpack tensor: h_scale_dq_all_inline598__rv_v2
    __gm__ PyPTORuntimeTensor* h_scale_dq_all_inline598__rv_v2_tensor = reinterpret_cast<__gm__ PyPTORuntimeTensor*>(args[6]);
    __gm__ float* h_scale_dq_all_inline598__rv_v2 = reinterpret_cast<__gm__ float*>(h_scale_dq_all_inline598__rv_v2_tensor->buffer.addr) + h_scale_dq_all_inline598__rv_v2_tensor->start_offset;

    // Unpack tensor: local_routed_weight__ssa_v1
    __gm__ PyPTORuntimeTensor* local_routed_weight__ssa_v1_tensor = reinterpret_cast<__gm__ PyPTORuntimeTensor*>(args[7]);
    __gm__ float* local_routed_weight__ssa_v1 = reinterpret_cast<__gm__ float*>(local_routed_weight__ssa_v1_tensor->buffer.addr) + local_routed_weight__ssa_v1_tensor->start_offset;

    // Unpack tensor: __gm_pipe_buffer
    __gm__ PyPTORuntimeTensor* __gm_pipe_buffer_tensor = reinterpret_cast<__gm__ PyPTORuntimeTensor*>(args[8]);
    // SPMD: index the fixed per-block GM pipe workspace.
    const int64_t kGmPipeFloatsPerBlock = 32768;
    int64_t __pypto_gm_block_offset =
        static_cast<int64_t>(__pypto_spmd_block_idx)
        * kGmPipeFloatsPerBlock;
    __gm__ float* __gm_pipe_buffer = reinterpret_cast<__gm__ float*>(__gm_pipe_buffer_tensor->buffer.addr) + __gm_pipe_buffer_tensor->start_offset + __pypto_gm_block_offset;

    // Unpack scalar: routed_workers_inline560__phi_v2
    union { uint64_t u64; int64_t val; } routed_workers_inline560__phi_v2_conv;
    routed_workers_inline560__phi_v2_conv.u64 = args[9];
    int64_t routed_workers_inline560__phi_v2 = routed_workers_inline560__phi_v2_conv.val;

    // Forward to ptoas-generated function
    expert_down_aiv(local_route_count__ssa_v0, local_routed_y__ssa_v0, local_expert_count__ssa_v1, h_i8_inline553__rv_v2, w_down_2d_inline571__ssa_v0, w_down_r_scale__ssa_v0, h_scale_dq_all_inline598__rv_v2, local_routed_weight__ssa_v1, __gm_pipe_buffer, routed_workers_inline560__phi_v2, __pypto_spmd_block_idx, __pypto_spmd_block_num, __pypto_spmd_subblock_idx);
}
