/*
 * Copyright (c) PyPTO Contributors.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * -----------------------------------------------------------------------------------------------------------
 */

// Kernel Function: routed_gmm1_swiglu7_quant_aiv
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#if !defined(__CPU_SIM)
#include "intrinsic.h"

// A2A3 mixed tasks run the same AIV kernel on two vector cores.
// Bridge the runtime-provided lane id into PTO-ISA get_subblockid().
[[block_local]] static int32_t pypto_runtime_subblock_id;
#define get_subblockid() pypto_runtime_subblock_id
#endif

#include <pto/pto-inst.hpp>
#include "runtime_tensor_compat.hpp"
#include "intrinsic.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
  dcci((__gm__ void*)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void routed_gmm1_swiglu_quant_aic(__gm__ int32_t* v1, __gm__ int32_t* v2, __gm__ int32_t* v3, __gm__ int8_t* v4, __gm__ int8_t* v5, __gm__ bfloat16_t* v6, __gm__ float* v7, __gm__ float* v8, __gm__ int8_t* v9, __gm__ float* v10, int32_t v11, int32_t v12) {
  const int64_t v13 = 128;
  const int64_t v14 = 16;
  const int64_t v15 = 15;
  const int64_t v16 = 2;
  const int64_t v17 = 256;
  const int64_t v18 = 24;
  const int64_t v19 = 10;
  const int64_t v20 = 4096;
  const int64_t v21 = 36;
  const int64_t v22 = 2560;
  const int64_t v23 = 1;
  const int64_t v24 = 0;
  using T = float;

  #if defined(__DAV_CUBE__)
  // pto: %core_inline582__ssa_v0
  // pto: %t__tile
  int32_t v25 = v1[v23];
  // pto: %0
  int64_t v26 = (int64_t) v25;
  set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
  set_flag(PIPE_FIX, PIPE_M, EVENT_ID0);
  set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID3);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
  // pto: %1, %active_expert_count_inline574__phi_v4, %3
  for (int64_t i27 = (int64_t) v11; i27 < ((int64_t) ((uint64_t) (v26 > v21 ? v21 : v26) * (uint64_t) v19)); i27 += v18) {
    // pto: %5, %6
    int64_t v28 = (int64_t) ((uint64_t) (i27 % v19) * (uint64_t) v17);
    // pto: %4, %8, %7
    int32_t v29 = v1[(int64_t) ((uint64_t) (i27 / v19) + (uint64_t) v16)];
    // pto: %9
    int64_t v30 = (int64_t) v29;
    // pto: %n_rows_inline541__tile
    int32_t v31 = v3[v30];
    // pto: %10
    int64_t v32 = (int64_t) v31;
    // pto: %11, %12
    for (int64_t j33 = v24; j33 < ((int64_t) ((uint64_t) v32 + (uint64_t) v15) / v14); j33 += v23) {
      // pto: %14
      int64_t v34 = (int64_t) ((uint64_t) j33 * (uint64_t) v14);
      // pto: %13, %15
      int64_t v35 = (int64_t) ((uint64_t) ((int64_t) ((uint64_t) v30 * (uint64_t) v13)) + (uint64_t) v34);
      // pto: %19
      int64_t v36 = (int64_t) ((uint64_t) v32 - (uint64_t) v34);
      // pto: %20
      int64_t v37 = v36 < v14 ? v36 : v14;
      // pto: %x0_mat_inline559__ssa_v0
      Tile<TileType::Mat, int8_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v38 = Tile<TileType::Mat, int8_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v37, v17);
      // pto: %x0_mat_inline559__ssa_v0
      uint64_t v39 = (uint64_t) v24;
      TASSIGN(v38, v39);
      // pto: %local_routed_x__ssa_v8_pview
      int64_t v40 = v37 * v20;
      // pto: %local_routed_x__ssa_v8_pview
      pto::Shape<1, 1, 1, -1, 256> v41 = pto::Shape<1, 1, 1, -1, 256>(v37);
      // pto: %local_routed_x__ssa_v8_pview
      pto::Stride<-1, -1, -1, 4096, 1> v42 = pto::Stride<-1, -1, -1, 4096, 1>(v40, v40, v40);
      // pto: %local_routed_x__ssa_v8_pview
      GlobalTensor<int8_t, pto::Shape<1, 1, 1, -1, 256>, pto::Stride<-1, -1, -1, 4096, 1>, pto::Layout::ND> v43 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, -1, 256>, pto::Stride<-1, -1, -1, 4096, 1>, pto::Layout::ND>(v4 + ((v24 + v35 * v20) + v24 * v23), v41, v42);
      wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
      TLOAD(v38, v43);
      set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
      // pto: %x0_inline535__ssa_v0
      Tile<TileType::Left, int8_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v44 = Tile<TileType::Left, int8_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v37, v17);
      // pto: %x0_inline535__ssa_v0
      uint64_t v45 = (uint64_t) v24;
      TASSIGN(v44, v45);
      wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
      TMOV(v44, v38);
      set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
      // pto: %w0_mat_inline540__ssa_v0
      Tile<TileType::Mat, int8_t, 256, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v46 = Tile<TileType::Mat, int8_t, 256, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v17, v17);
      // pto: %w0_mat_inline540__ssa_v0
      uint64_t v47 = (uint64_t) v24;
      TASSIGN(v46, v47);
      // pto: %22
      int64_t v48 = (int64_t) ((uint64_t) v30 * (uint64_t) v20);
      // pto: %w13_2d_inline549__ssa_v0_pview
      pto::Shape<1, 8, 16, 16, 32> v49 = pto::Shape<1, 8, 16, 16, 32>();
      // pto: %w13_2d_inline549__ssa_v0_pview
      pto::Stride<1048576, 131072, 512, 32, 1> v50 = pto::Stride<1048576, 131072, 512, 32, 1>();
      // pto: %w13_2d_inline549__ssa_v0_pview
      GlobalTensor<int8_t, pto::Shape<1, 8, 16, 16, 32>, pto::Stride<1048576, 131072, 512, 32, 1>, pto::Layout::NZ> v51 = GlobalTensor<int8_t, pto::Shape<1, 8, 16, 16, 32>, pto::Stride<1048576, 131072, 512, 32, 1>, pto::Layout::NZ>(v5 + v48 * v22 + (v28 / 32) * 131072, v49, v50);
      wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
      TLOAD(v46, v51);
      set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID1);
      // pto: %w0_inline567__ssa_v0
      Tile<TileType::Right, int8_t, 256, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v52 = Tile<TileType::Right, int8_t, 256, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v17, v17);
      // pto: %w0_inline567__ssa_v0
      uint64_t v53 = (uint64_t) v24;
      TASSIGN(v52, v53);
      wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID1);
      TMOV(v52, v46);
      set_flag(PIPE_MTE1, PIPE_M, EVENT_ID0);
      set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID2);
      // pto: %gate_up_acc_inline578__ssa_v0
      Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v54 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v14, v17);
      // pto: %gate_up_acc_inline578__ssa_v0
      uint64_t v55 = (uint64_t) v24;
      TASSIGN(v54, v55);
      wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID0);
      wait_flag(PIPE_FIX, PIPE_M, EVENT_ID0);
      TMATMUL(v54, v44, v52);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
      wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID2);
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
      for (int64_t k56 = v23; k56 < v14; k56 += v23) {
        // pto: %23
        int64_t v57 = (int64_t) ((uint64_t) k56 * (uint64_t) v17);
        // pto: %xk_mat_inline577__ssa_v0
        Tile<TileType::Mat, int8_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v58 = Tile<TileType::Mat, int8_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v37, v17);
        // pto: %xk_mat_inline577__ssa_v0
        uint64_t v59 = (uint64_t) v24;
        TASSIGN(v58, v59);
        // pto: %24
        int64_t v60 = v37 * v20;
        // pto: %24
        pto::Shape<1, 1, 1, -1, 256> v61 = pto::Shape<1, 1, 1, -1, 256>(v37);
        // pto: %24
        pto::Stride<-1, -1, -1, 4096, 1> v62 = pto::Stride<-1, -1, -1, 4096, 1>(v60, v60, v60);
        // pto: %24
        GlobalTensor<int8_t, pto::Shape<1, 1, 1, -1, 256>, pto::Stride<-1, -1, -1, 4096, 1>, pto::Layout::ND> v63 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, -1, 256>, pto::Stride<-1, -1, -1, 4096, 1>, pto::Layout::ND>(v4 + ((v24 + v35 * v20) + v57 * v23), v61, v62);
        wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID3);
        TLOAD(v58, v63);
        set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID2);
        // pto: %xk_inline536__ssa_v0
        Tile<TileType::Left, int8_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v64 = Tile<TileType::Left, int8_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v37, v17);
        // pto: %xk_inline536__ssa_v0
        uint64_t v65 = (uint64_t) v24;
        TASSIGN(v64, v65);
        wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID2);
        wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
        TMOV(v64, v58);
        set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID4);
        // pto: %wk_mat_inline594__ssa_v0
        Tile<TileType::Mat, int8_t, 256, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v66 = Tile<TileType::Mat, int8_t, 256, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v17, v17);
        // pto: %wk_mat_inline594__ssa_v0
        uint64_t v67 = (uint64_t) v24;
        TASSIGN(v66, v67);
        // pto: %27
        pto::Shape<1, 8, 16, 16, 32> v68 = pto::Shape<1, 8, 16, 16, 32>();
        // pto: %27
        pto::Stride<1048576, 131072, 512, 32, 1> v69 = pto::Stride<1048576, 131072, 512, 32, 1>();
        // pto: %26, %27
        GlobalTensor<int8_t, pto::Shape<1, 8, 16, 16, 32>, pto::Stride<1048576, 131072, 512, 32, 1>, pto::Layout::NZ> v70 = GlobalTensor<int8_t, pto::Shape<1, 8, 16, 16, 32>, pto::Stride<1048576, 131072, 512, 32, 1>, pto::Layout::NZ>(v5 + v48 * v22 + (v57 / 16) * 512 + (v28 / 32) * 131072, v68, v69);
        wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID4);
        TLOAD(v66, v70);
        set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID3);
        // pto: %wk_inline542__ssa_v0
        Tile<TileType::Right, int8_t, 256, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v71 = Tile<TileType::Right, int8_t, 256, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v17, v17);
        // pto: %wk_inline542__ssa_v0
        uint64_t v72 = (uint64_t) v24;
        TASSIGN(v71, v72);
        wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID3);
        TMOV(v71, v66);
        set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID3);
        set_flag(PIPE_MTE1, PIPE_M, EVENT_ID1);
        // pto: %gate_up_acc_inline578__ssa_v3
        Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v73 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v14, v17);
        // pto: %gate_up_acc_inline578__ssa_v3
        uint64_t v74 = (uint64_t) v24;
        TASSIGN(v73, v74);
        wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID1);
        TMATMUL_ACC(v73, v73, v64, v71);
        set_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
      }
      set_flag(PIPE_M, PIPE_FIX, EVENT_ID0);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
      set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
      // pto: %gate_up_i32_inline575__iter_v3_pview
      pto::Shape<1, 1, 1, 16, 256> v75 = pto::Shape<1, 1, 1, 16, 256>();
      // pto: %gate_up_i32_inline575__iter_v3_pview
      pto::Stride<40960, 40960, 40960, 2560, 1> v76 = pto::Stride<40960, 40960, 40960, 2560, 1>();
      // pto: %gate_up_i32_inline575__iter_v3_pview
      GlobalTensor<int32_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<40960, 40960, 40960, 2560, 1>, pto::Layout::ND> v77 = GlobalTensor<int32_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<40960, 40960, 40960, 2560, 1>, pto::Layout::ND>(v2 + ((v24 + v35 * v22) + v28 * v23), v75, v76);
      wait_flag(PIPE_M, PIPE_FIX, EVENT_ID0);
      TSTORE(v77, v54);
      set_flag(PIPE_FIX, PIPE_M, EVENT_ID0);
    }
  }
  wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
  wait_flag(PIPE_FIX, PIPE_M, EVENT_ID0);
  wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID3);
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
  // PYPTO-LIB-AUTHORITY: cross-core-gate-up-publish begin
  // The first mixed-core barrier does not publish the AIC FIXPIPE stores.
  // Drain and flush gate_up_i32 before AIV consumers cross the rendezvous.
  pipe_barrier(PIPE_ALL);
  dcci(static_cast<__gm__ void *>(0), ENTIRE_DATA_CACHE);
  dsb(DSB_DDR);
  // PYPTO-LIB-AUTHORITY: cross-core-gate-up-publish end
  SYNCALL<SyncCoreType::Mix>();
  SYNCALL<SyncCoreType::Mix>();
  #endif // __DAV_CUBE__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

static __aicore__ void routed_gmm1_swiglu_quant_aiv(__gm__ int32_t* v1, __gm__ int32_t* v2, __gm__ int32_t* v3, __gm__ int8_t* v4, __gm__ int8_t* v5, __gm__ bfloat16_t* v6, __gm__ float* v7, __gm__ float* v8, __gm__ int8_t* v9, __gm__ float* v10, int32_t v11, int32_t v12, int32_t v13) {
  RoundMode v14 = RoundMode::CAST_TRUNC;
  RoundMode v15 = RoundMode::CAST_RINT;
  RoundMode v16 = RoundMode::CAST_ROUND;
  SaturationMode v17 = SaturationMode::OFF;
  RoundMode v18 = RoundMode::CAST_NONE;
  const float v19 = 127.0f;
  const float v20 = 9.99999974E-5f;
  const float v21 = 1.0f;
  const float kSwigluMin = -7.0f;
  const float kSwigluMax = 7.0f;
  const int64_t v22 = 8;
  const int64_t v23 = 128;
  const int64_t v24 = 16;
  const int64_t v25 = 15;
  const int64_t v26 = 2;
  const int64_t v27 = 256;
  const int64_t v28 = 24;
  const int64_t v29 = 5;
  const int64_t v30 = 1280;
  const int64_t v31 = 36;
  const int64_t v32 = 2560;
  const int64_t v33 = 4608;
  const int64_t v34 = 1;
  const int64_t v35 = 32800;
  const int64_t v36 = 24608;
  const int64_t v37 = 16416;
  const int64_t v38 = 16384;
  const int64_t v39 = 8192;
  const int64_t v40 = 0;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  // pto: %subblock_idx, %54
  set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  set_flag(PIPE_MTE3, PIPE_V, EVENT_ID1);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID3);
  set_flag(PIPE_MTE3, PIPE_V, EVENT_ID3);
  if ((int64_t) v13 == v40) {
    // pto: %core_inline582__ssa_v0
    int64_t v41 = (int64_t) v11;
    // pto: %55
    int32_t v42 = v1[v34];
    // pto: %56
    int64_t v43 = (int64_t) v42;
    // pto: %57, %active_expert_count_inline574__phi_v4
    int64_t v44 = v43 > v31 ? v31 : v43;
    // PYPTO-LIB-AUTHORITY: cross-core-gate-up-acquire begin
    SYNCALL<SyncCoreType::Mix>();
    dcci(static_cast<__gm__ void *>(0), ENTIRE_DATA_CACHE);
    dsb(DSB_DDR);
    // PYPTO-LIB-AUTHORITY: cross-core-gate-up-acquire end
    // pto: %59
    for (int64_t i45 = v41; i45 < ((int64_t) ((uint64_t) v44 * (uint64_t) v29)); i45 += v28) {
      // pto: %61, %62
      int64_t v46 = (int64_t) ((uint64_t) (i45 % v29) * (uint64_t) v27);
      // pto: %63
      int64_t v47 = (int64_t) ((uint64_t) v46 + (uint64_t) v30);
      // pto: %60, %65, %64
      int32_t v48 = v1[(int64_t) ((uint64_t) (i45 / v29) + (uint64_t) v26)];
      // pto: %66
      int64_t v49 = (int64_t) v48;
      // pto: %n_rows_inline541__tile
      int32_t v50 = v3[v49];
      // pto: %67
      int64_t v51 = (int64_t) v50;
      // pto: %68, %69
      for (int64_t j52 = v40; j52 < ((int64_t) ((uint64_t) v51 + (uint64_t) v25) / v24); j52 += v34) {
        // pto: %71
        int64_t v53 = (int64_t) ((uint64_t) j52 * (uint64_t) v24);
        for (int64_t k54 = v40; k54 < v26; k54 += v34) {
          // pto: %73
          int64_t v55 = (int64_t) ((uint64_t) k54 * (uint64_t) v22);
          // pto: %75, %76
          int64_t v56 = v51 - v53 - v55;
          // pto: %70, %72, %79
          int64_t v60 = (int64_t) ((uint64_t) ((int64_t) ((uint64_t) ((int64_t) ((uint64_t) v49 * (uint64_t) v23)) + (uint64_t) v53)) + (uint64_t) v55);
          const int64_t remaining_rows = v56;
          const int64_t output_row = v60;
          // PYPTO-LIB-AUTHORITY: empty-row-part-zero-store begin
          if (remaining_rows > v40) {
          // pto: %77, %part_valid_inline589__phi_v4
          int64_t v57 = remaining_rows > v22 ? v22 : remaining_rows;
          // pto: %t__tmp_v145
          Tile<TileType::Vec, int32_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v58 = Tile<TileType::Vec, int32_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v57, v27);
          // pto: %t__tmp_v145
          uint64_t v59 = (uint64_t) v40;
          TASSIGN(v58, v59);
          // pto: %gate_up_i32_inline575__ssa_v0_pview
          int64_t v61 = v57 * v32;
          // pto: %gate_up_i32_inline575__ssa_v0_pview
          pto::Shape<1, 1, 1, -1, 256> v62 = pto::Shape<1, 1, 1, -1, 256>(v57);
          // pto: %gate_up_i32_inline575__ssa_v0_pview
          pto::Stride<-1, -1, -1, 2560, 1> v63 = pto::Stride<-1, -1, -1, 2560, 1>(v61, v61, v61);
          // pto: %gate_up_i32_inline575__ssa_v0_pview
          GlobalTensor<int32_t, pto::Shape<1, 1, 1, -1, 256>, pto::Stride<-1, -1, -1, 2560, 1>, pto::Layout::ND> v64 = GlobalTensor<int32_t, pto::Shape<1, 1, 1, -1, 256>, pto::Stride<-1, -1, -1, 2560, 1>, pto::Layout::ND>(v2 + ((v40 + v60 * v32) + v46 * v34), v62, v63);
          wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
          TLOAD(v58, v64);
          set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
          // pto: %gate_acc_inline592__ssa_v0
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v65 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v57, v27);
          // pto: %gate_acc_inline592__ssa_v0
          uint64_t v66 = (uint64_t) v40;
          TASSIGN(v65, v66);
          wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
          TCVT(v65, v58, v18, v17);
          // pto: %t__tmp_v146
          Tile<TileType::Vec, int32_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v67 = Tile<TileType::Vec, int32_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v57, v27);
          // pto: %t__tmp_v146
          uint64_t v68 = (uint64_t) v39;
          TASSIGN(v67, v68);
          // pto: %81
          int64_t v69 = v57 * v32;
          // pto: %81
          pto::Shape<1, 1, 1, -1, 256> v70 = pto::Shape<1, 1, 1, -1, 256>(v57);
          // pto: %81
          pto::Stride<-1, -1, -1, 2560, 1> v71 = pto::Stride<-1, -1, -1, 2560, 1>(v69, v69, v69);
          // pto: %81
          GlobalTensor<int32_t, pto::Shape<1, 1, 1, -1, 256>, pto::Stride<-1, -1, -1, 2560, 1>, pto::Layout::ND> v72 = GlobalTensor<int32_t, pto::Shape<1, 1, 1, -1, 256>, pto::Stride<-1, -1, -1, 2560, 1>, pto::Layout::ND>(v2 + ((v40 + v60 * v32) + v47 * v34), v70, v71);
          TLOAD(v67, v72);
          set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
          // pto: %up_acc_inline572__ssa_v0
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v73 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v57, v27);
          // pto: %up_acc_inline572__ssa_v0
          uint64_t v74 = (uint64_t) v39;
          TASSIGN(v73, v74);
          wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
          TCVT(v73, v67, v18, v17);
          // pto: %x_scale_row_inline593__ssa_v0
          Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v75 = Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v34, v57);
          // pto: %x_scale_row_inline593__ssa_v0
          uint64_t v76 = (uint64_t) v38;
          TASSIGN(v75, v76);
          // pto: %local_routed_x_scale__ssa_v1_pview
          pto::Shape<1, 1, 1, 1, -1> v77 = pto::Shape<1, 1, 1, 1, -1>(v57);
          // pto: %local_routed_x_scale__ssa_v1_pview
          pto::Stride<4608, 4608, 4608, 4608, 1> v78 = pto::Stride<4608, 4608, 4608, 4608, 1>();
          // pto: %local_routed_x_scale__ssa_v1_pview
          GlobalTensor<float, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<4608, 4608, 4608, 4608, 1>, pto::Layout::ND> v79 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, -1>, pto::Stride<4608, 4608, 4608, 4608, 1>, pto::Layout::ND>(v7 + ((v40 + v40 * v33) + v60 * v34), v77, v78);
          TLOAD(v75, v79);
          set_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
          // pto: %x_scale_col_inline595__ssa_v0
          Tile<TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v80 = Tile<TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v22, v34);
          // pto: %x_scale_col_inline595__ssa_v0
          uint64_t v81 = (uint64_t) v38;
          TASSIGN(v80, v81);
          // pto: %wg_scale_row_inline597__ssa_v0
          Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v82 = Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v34, v27);
          // pto: %wg_scale_row_inline597__ssa_v0
          uint64_t v83 = (uint64_t) v37;
          TASSIGN(v82, v83);
          // pto: %w13_r_scale__ssa_v0_pview
          pto::Shape<1, 1, 1, 1, 256> v84 = pto::Shape<1, 1, 1, 1, 256>();
          // pto: %w13_r_scale__ssa_v0_pview
          pto::Stride<2560, 2560, 2560, 2560, 1> v85 = pto::Stride<2560, 2560, 2560, 2560, 1>();
          // pto: %w13_r_scale__ssa_v0_pview
          GlobalTensor<float, pto::Shape<1, 1, 1, 1, 256>, pto::Stride<2560, 2560, 2560, 2560, 1>, pto::Layout::ND> v86 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 256>, pto::Stride<2560, 2560, 2560, 2560, 1>, pto::Layout::ND>(v8 + ((v40 + v49 * v32) + v46 * v34), v84, v85);
          TLOAD(v82, v86);
          set_flag(PIPE_MTE2, PIPE_V, EVENT_ID3);
          // pto: %wu_scale_row_inline548__ssa_v0
          Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v87 = Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v34, v27);
          // pto: %wu_scale_row_inline548__ssa_v0
          uint64_t v88 = (uint64_t) v36;
          TASSIGN(v87, v88);
          // pto: %83
          pto::Shape<1, 1, 1, 1, 256> v89 = pto::Shape<1, 1, 1, 1, 256>();
          // pto: %83
          pto::Stride<2560, 2560, 2560, 2560, 1> v90 = pto::Stride<2560, 2560, 2560, 2560, 1>();
          // pto: %83
          GlobalTensor<float, pto::Shape<1, 1, 1, 1, 256>, pto::Stride<2560, 2560, 2560, 2560, 1>, pto::Layout::ND> v91 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 256>, pto::Stride<2560, 2560, 2560, 2560, 1>, pto::Layout::ND>(v8 + ((v40 + v49 * v32) + v47 * v34), v89, v90);
          TLOAD(v87, v91);
          set_flag(PIPE_MTE2, PIPE_V, EVENT_ID4);
          // pto: %t__tmp_v147
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v92 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v57, v27);
          // pto: %t__tmp_v147
          uint64_t v93 = (uint64_t) v40;
          TASSIGN(v92, v93);
          wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
          pipe_barrier(PIPE_V);
          TROWEXPANDMUL(v92, v65, v80);
          // pto: %gate_2d_inline599__ssa_v0
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v94 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v57, v27);
          // pto: %gate_2d_inline599__ssa_v0
          uint64_t v95 = (uint64_t) v40;
          TASSIGN(v94, v95);
          pipe_barrier(PIPE_V);
          wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID3);
          TCOLEXPANDMUL(v94, v92, v82);
          // pto: %t__tmp_v148
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v96 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v57, v27);
          // pto: %t__tmp_v148
          uint64_t v97 = (uint64_t) v39;
          TASSIGN(v96, v97);
          TROWEXPANDMUL(v96, v73, v80);
          // pto: %up_2d_inline600__ssa_v0
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v98 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v57, v27);
          // pto: %up_2d_inline600__ssa_v0
          uint64_t v99 = (uint64_t) v39;
          TASSIGN(v98, v99);
          pipe_barrier(PIPE_V);
          wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID4);
          TCOLEXPANDMUL(v98, v96, v87);
          // pto: %t__tmp_v149
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v100 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v57, v27);
          // pto: %t__tmp_v149
          uint64_t v101 = (uint64_t) v37;
          TASSIGN(v100, v101);
          TNEG(v100, v94);
          // pto: %t__tmp_v150
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v102 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v57, v27);
          // pto: %t__tmp_v150
          uint64_t v103 = (uint64_t) v37;
          TASSIGN(v102, v103);
          pipe_barrier(PIPE_V);
          TEXP(v102, v100);
          // pto: %t__tmp_v151
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v104 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v57, v27);
          // pto: %t__tmp_v151
          uint64_t v105 = (uint64_t) v37;
          TASSIGN(v104, v105);
          pipe_barrier(PIPE_V);
          TADDS(v104, v102, v21);
          // pto: %sigmoid_inline591__ssa_v0
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v106 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v57, v27);
          // pto: %sigmoid_inline591__ssa_v0
          uint64_t v107 = (uint64_t) v36;
          TASSIGN(v106, v107);
          pipe_barrier(PIPE_V);
          TRECIP(v106, v104);
          // pto: %silu_inline602__ssa_v0
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v108 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v57, v27);
          // pto: %silu_inline602__ssa_v0
          uint64_t v109 = (uint64_t) v40;
          TASSIGN(v108, v109);
          pipe_barrier(PIPE_V);
          TMUL(v108, v94, v106);
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> swiglu_silu_clamped = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v57, v27);
          TASSIGN(swiglu_silu_clamped, (uint64_t) v40);
          pipe_barrier(PIPE_V);
          TMINS(swiglu_silu_clamped, v108, kSwigluMax);
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> swiglu_up_upper = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v57, v27);
          TASSIGN(swiglu_up_upper, (uint64_t) v39);
          pipe_barrier(PIPE_V);
          TMINS(swiglu_up_upper, v98, kSwigluMax);
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> swiglu_up_clamped = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v57, v27);
          TASSIGN(swiglu_up_clamped, (uint64_t) v39);
          pipe_barrier(PIPE_V);
          TMAXS(swiglu_up_clamped, swiglu_up_upper, kSwigluMin);
          // pto: %gated_inline607__ssa_v1
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v110 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v57, v27);
          // pto: %gated_inline607__ssa_v1
          uint64_t v111 = (uint64_t) v40;
          TASSIGN(v110, v111);
          pipe_barrier(PIPE_V);
          TMUL(v110, swiglu_silu_clamped, swiglu_up_clamped);
          v110.SetValidShape(v57, v27);
          // pto: %gated_m_inline586__ssa_v0
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null> v112 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null>(v22, v27);
          // pto: %gated_m_inline586__ssa_v0
          uint64_t v113 = (uint64_t) v40;
          TASSIGN(v112, v113);
          pipe_barrier(PIPE_V);
          TFILLPAD(v112, v110);
          // pto: %t__tmp_v152
          Tile<TileType::Vec, bfloat16_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null> v114 = Tile<TileType::Vec, bfloat16_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null>(v22, v27);
          // pto: %t__tmp_v152
          uint64_t v115 = (uint64_t) v40;
          TASSIGN(v114, v115);
          pipe_barrier(PIPE_V);
          TCVT(v114, v112, v16, v17);
          set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
          // pto: %h_bf16_inline547__iter_v5_pview
          pto::Shape<1, 1, 1, 8, 256> v116 = pto::Shape<1, 1, 1, 8, 256>();
          // pto: %h_bf16_inline547__iter_v5_pview
          pto::Stride<10240, 10240, 10240, 1280, 1> v117 = pto::Stride<10240, 10240, 10240, 1280, 1>();
          // pto: %h_bf16_inline547__iter_v5_pview
          GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 8, 256>, pto::Stride<10240, 10240, 10240, 1280, 1>, pto::Layout::ND> v118 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 8, 256>, pto::Stride<10240, 10240, 10240, 1280, 1>, pto::Layout::ND>(v6 + ((v40 + v60 * v30) + v46 * v34), v116, v117);
          wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
          TSTORE(v118, v114);
          set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
          } else {
            // Materialize the empty half consumed by fixed-shape quantization.
            wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
            pipe_barrier(PIPE_ALL);
            Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null> empty_part_f32 =
                Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null>(v22, v27);
            TASSIGN(empty_part_f32, (uint64_t) v40);
            TEXPANDS(empty_part_f32, 0.0f);
            Tile<TileType::Vec, bfloat16_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null> empty_part_bf16 =
                Tile<TileType::Vec, bfloat16_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null>(v22, v27);
            TASSIGN(empty_part_bf16, (uint64_t) v40);
            pipe_barrier(PIPE_V);
            TCVT(empty_part_bf16, empty_part_f32, v16, v17);
            set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
            pto::Shape<1, 1, 1, 8, 256> empty_part_shape =
                pto::Shape<1, 1, 1, 8, 256>();
            pto::Stride<10240, 10240, 10240, 1280, 1> empty_part_stride =
                pto::Stride<10240, 10240, 10240, 1280, 1>();
            GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 8, 256>, pto::Stride<10240, 10240, 10240, 1280, 1>, pto::Layout::ND> empty_part_out =
                GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 8, 256>, pto::Stride<10240, 10240, 10240, 1280, 1>, pto::Layout::ND>(
                    v6 + ((v40 + output_row * v30) + v46 * v34),
                    empty_part_shape,
                    empty_part_stride);
            wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
            TSTORE(empty_part_out, empty_part_bf16);
            set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
          }
          // PYPTO-LIB-AUTHORITY: empty-row-part-zero-store end
        }
      }
    }
    set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
    // PYPTO-LIB-AUTHORITY: cross-core-h-bf16-publish begin
    // SYNCALL is only a rendezvous. Drain each producer's TSTOREs to DDR
    // before the barrier, then invalidate the readers' data cache afterwards.
    pipe_barrier(PIPE_ALL);
    dcci(static_cast<__gm__ void *>(0), ENTIRE_DATA_CACHE);
    dsb(DSB_DDR);
    SYNCALL<SyncCoreType::Mix>();
    dcci(static_cast<__gm__ void *>(0), ENTIRE_DATA_CACHE);
    dsb(DSB_DDR);
    // PYPTO-LIB-AUTHORITY: cross-core-h-bf16-publish end
    for (int64_t i119 = v41; i119 < v44; i119 += v28) {
      // pto: %86, %85
      int32_t v120 = v1[(int64_t) ((uint64_t) i119 + (uint64_t) v26)];
      // pto: %87
      int64_t v121 = (int64_t) v120;
      // pto: %88
      int32_t v122 = v3[v121];
      // pto: %89, %90, %91
      for (int64_t j123 = v40; j123 < ((int64_t) ((uint64_t) ((int64_t) v122) + (uint64_t) v25) / v24); j123 += v34) {
        for (int64_t k124 = v40; k124 < v26; k124 += v34) {
          // pto: %92, %94, %93, %96, %95
          int64_t v125 = (int64_t) ((uint64_t) ((int64_t) ((uint64_t) ((int64_t) ((uint64_t) v121 * (uint64_t) v23)) + (uint64_t) ((int64_t) ((uint64_t) j123 * (uint64_t) v24)))) + (uint64_t) ((int64_t) ((uint64_t) k124 * (uint64_t) v22)));
          // pto: %eh_amax_inline531__tile
          Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v126 = Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v34, v22);
          // pto: %eh_amax_inline531__tile
          uint64_t v127 = (uint64_t) v37;
          TASSIGN(v126, v127);
          TEXPANDS(v126, v20);
          wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
          wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID1);
          for (int64_t l128 = v40; l128 < v29; l128 += v34) {
            // pto: %t__tile
            Tile<TileType::Vec, bfloat16_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v129 = Tile<TileType::Vec, bfloat16_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v22, v27);
            // pto: %t__tile
            uint64_t v130 = (uint64_t) v39;
            TASSIGN(v129, v130);
            // pto: %h_bf16_inline547__rv_v2_pview
            pto::Shape<1, 1, 1, 8, 256> v131 = pto::Shape<1, 1, 1, 8, 256>();
            // pto: %h_bf16_inline547__rv_v2_pview
            pto::Stride<10240, 10240, 10240, 1280, 1> v132 = pto::Stride<10240, 10240, 10240, 1280, 1>();
            // pto: %h_bf16_inline547__rv_v2_pview, %97
            GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 8, 256>, pto::Stride<10240, 10240, 10240, 1280, 1>, pto::Layout::ND> v133 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 8, 256>, pto::Stride<10240, 10240, 10240, 1280, 1>, pto::Layout::ND>(v6 + ((v40 + v125 * v30) + (int64_t) ((uint64_t) l128 * (uint64_t) v27) * v34), v131, v132);
            wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
            TLOAD(v129, v133);
            set_flag(PIPE_MTE2, PIPE_V, EVENT_ID5);
            // pto: %eh_a_inline527__tile
            Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v134 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v22, v27);
            // pto: %eh_a_inline527__tile
            uint64_t v135 = (uint64_t) v40;
            TASSIGN(v134, v135);
            wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID5);
            TCVT(v134, v129, v16, v17);
            // pto: %0
            Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v136 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v22, v27);
            // pto: %0
            uint64_t v137 = (uint64_t) v39;
            TASSIGN(v136, v137);
            pipe_barrier(PIPE_V);
            TNEG(v136, v134);
            // pto: %1
            Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v138 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v22, v27);
            // pto: %1
            uint64_t v139 = (uint64_t) v40;
            TASSIGN(v138, v139);
            pipe_barrier(PIPE_V);
            TMAX(v138, v134, v136);
            // pto: %tmp_tile
            Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v140 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v22, v27);
            // pto: %tmp_tile
            uint64_t v141 = (uint64_t) v39;
            TASSIGN(v140, v141);
            // pto: %2
            Tile<TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v142 = Tile<TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v22, v34);
            // pto: %2
            uint64_t v143 = (uint64_t) v35;
            TASSIGN(v142, v143);
            pipe_barrier(PIPE_V);
            TROWMAX(v142, v138, v140);
            set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
            // pto: %3
            Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v144 = Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v34, v22);
            // pto: %3
            uint64_t v145 = (uint64_t) v35;
            TASSIGN(v144, v145);
            // pto: %4
            Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v146 = Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v34, v22);
            // pto: %4
            uint64_t v147 = (uint64_t) v37;
            TASSIGN(v146, v147);
            pipe_barrier(PIPE_V);
            TMAX(v146, v126, v144);
          }
          // pto: %5
          Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v148 = Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v34, v22);
          // pto: %5
          uint64_t v149 = (uint64_t) v40;
          TASSIGN(v148, v149);
          pipe_barrier(PIPE_V);
          TRECIP(v148, v126);
          // pto: %6
          Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v150 = Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v34, v22);
          // pto: %6
          uint64_t v151 = (uint64_t) v39;
          TASSIGN(v150, v151);
          TEXPANDS(v150, v19);
          // pto: %eh_sq_row_inline525__tile
          Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v152 = Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v34, v22);
          // pto: %eh_sq_row_inline525__tile
          uint64_t v153 = (uint64_t) v37;
          TASSIGN(v152, v153);
          pipe_barrier(PIPE_V);
          TMUL(v152, v148, v150);
          set_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
          // pto: %7
          Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v154 = Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v34, v22);
          // pto: %7
          uint64_t v155 = (uint64_t) v40;
          TASSIGN(v154, v155);
          pipe_barrier(PIPE_V);
          TRECIP(v154, v152);
          set_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
          // pto: %8
          Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v156 = Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v34, v22);
          // pto: %8
          uint64_t v157 = (uint64_t) v40;
          TASSIGN(v156, v157);
          // pto: %h_scale_dq_all_inline598__iter_v5_pview
          pto::Shape<1, 1, 1, 1, 8> v158 = pto::Shape<1, 1, 1, 1, 8>();
          // pto: %h_scale_dq_all_inline598__iter_v5_pview
          pto::Stride<4608, 4608, 4608, 4608, 1> v159 = pto::Stride<4608, 4608, 4608, 4608, 1>();
          // pto: %h_scale_dq_all_inline598__iter_v5_pview
          GlobalTensor<float, pto::Shape<1, 1, 1, 1, 8>, pto::Stride<4608, 4608, 4608, 4608, 1>, pto::Layout::ND> v160 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 8>, pto::Stride<4608, 4608, 4608, 4608, 1>, pto::Layout::ND>(v10 + ((v40 + v40 * v33) + v125 * v34), v158, v159);
          wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
          TSTORE(v160, v156);
          set_flag(PIPE_MTE3, PIPE_V, EVENT_ID2);
          // pto: %eh_sq_col_inline538__tile
          Tile<TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v161 = Tile<TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v22, v34);
          // pto: %eh_sq_col_inline538__tile
          uint64_t v162 = (uint64_t) v37;
          TASSIGN(v161, v162);
          wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
          wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID2);
          for (int64_t l163 = v40; l163 < v29; l163 += v34) {
            // pto: %98
            int64_t v164 = (int64_t) ((uint64_t) l163 * (uint64_t) v27);
            // pto: %9
            Tile<TileType::Vec, bfloat16_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v165 = Tile<TileType::Vec, bfloat16_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v22, v27);
            // pto: %9
            uint64_t v166 = (uint64_t) v39;
            TASSIGN(v165, v166);
            // pto: %99
            pto::Shape<1, 1, 1, 8, 256> v167 = pto::Shape<1, 1, 1, 8, 256>();
            // pto: %99
            pto::Stride<10240, 10240, 10240, 1280, 1> v168 = pto::Stride<10240, 10240, 10240, 1280, 1>();
            // pto: %99
            GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 8, 256>, pto::Stride<10240, 10240, 10240, 1280, 1>, pto::Layout::ND> v169 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 8, 256>, pto::Stride<10240, 10240, 10240, 1280, 1>, pto::Layout::ND>(v6 + ((v40 + v125 * v30) + v164 * v34), v167, v168);
            wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID3);
            TLOAD(v165, v169);
            set_flag(PIPE_MTE2, PIPE_V, EVENT_ID6);
            // pto: %eh_q_inline564__tile
            Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v170 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v22, v27);
            // pto: %eh_q_inline564__tile
            uint64_t v171 = (uint64_t) v40;
            TASSIGN(v170, v171);
            wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID6);
            wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID3);
            TCVT(v170, v165, v16, v17);
            set_flag(PIPE_V, PIPE_MTE2, EVENT_ID3);
            // pto: %eh_scaled_inline522__tile
            Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v172 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v22, v27);
            // pto: %eh_scaled_inline522__tile
            uint64_t v173 = (uint64_t) v40;
            TASSIGN(v172, v173);
            pipe_barrier(PIPE_V);
            TROWEXPANDMUL(v172, v170, v161);
            // pto: %eh_i32_inline521__tile
            Tile<TileType::Vec, int32_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v174 = Tile<TileType::Vec, int32_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v22, v27);
            // pto: %eh_i32_inline521__tile
            uint64_t v175 = (uint64_t) v40;
            TASSIGN(v174, v175);
            pipe_barrier(PIPE_V);
            TCVT(v174, v172, v15, v17);
            // pto: %eh_half_inline534__tile
            Tile<TileType::Vec, half, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v176 = Tile<TileType::Vec, half, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v22, v27);
            // pto: %eh_half_inline534__tile
            uint64_t v177 = (uint64_t) v40;
            TASSIGN(v176, v177);
            pipe_barrier(PIPE_V);
            TCVT(v176, v174, v16, v17);
            // pto: %10
            Tile<TileType::Vec, int8_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v178 = Tile<TileType::Vec, int8_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v22, v27);
            // pto: %10
            uint64_t v179 = (uint64_t) v40;
            TASSIGN(v178, v179);
            pipe_barrier(PIPE_V);
            TCVT(v178, v176, v14, v17);
            set_flag(PIPE_V, PIPE_MTE3, EVENT_ID2);
            // pto: %h_i8_inline553__iter_v7_pview
            pto::Shape<1, 1, 1, 8, 256> v180 = pto::Shape<1, 1, 1, 8, 256>();
            // pto: %h_i8_inline553__iter_v7_pview
            pto::Stride<10240, 10240, 10240, 1280, 1> v181 = pto::Stride<10240, 10240, 10240, 1280, 1>();
            // pto: %h_i8_inline553__iter_v7_pview
            GlobalTensor<int8_t, pto::Shape<1, 1, 1, 8, 256>, pto::Stride<10240, 10240, 10240, 1280, 1>, pto::Layout::ND> v182 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 8, 256>, pto::Stride<10240, 10240, 10240, 1280, 1>, pto::Layout::ND>(v9 + ((v40 + v125 * v30) + v164 * v34), v180, v181);
            wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID2);
            TSTORE(v182, v178);
            set_flag(PIPE_MTE3, PIPE_V, EVENT_ID3);
          }
          set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
          set_flag(PIPE_MTE3, PIPE_V, EVENT_ID1);
        }
      }
    }
  } else {
    // pto: %100
    int64_t v183 = (int64_t) v11;
    // pto: %101
    int32_t v184 = v1[v34];
    // pto: %102
    int64_t v185 = (int64_t) v184;
    // pto: %103, %104
    int64_t v186 = v185 > v31 ? v31 : v185;
    // PYPTO-LIB-AUTHORITY: cross-core-gate-up-acquire begin
    SYNCALL<SyncCoreType::Mix>();
    dcci(static_cast<__gm__ void *>(0), ENTIRE_DATA_CACHE);
    dsb(DSB_DDR);
    // PYPTO-LIB-AUTHORITY: cross-core-gate-up-acquire end
    // pto: %106
    for (int64_t i187 = v183; i187 < ((int64_t) ((uint64_t) v186 * (uint64_t) v29)); i187 += v28) {
      // pto: %108, %110, %109
      int32_t v188 = v1[(int64_t) ((uint64_t) (i187 / v29) + (uint64_t) v26)];
      // pto: %111, %112
      int32_t v189 = v3[(int64_t) v188];
      // pto: %113, %114, %115
      for (int64_t j190 = v40; j190 < ((int64_t) ((uint64_t) ((int64_t) v189) + (uint64_t) v25) / v24); j190 += v34) {
        for (int64_t k191 = v40; k191 < v26; k191 += v34) {
          // pto: %11
          Tile<TileType::Vec, int32_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v192 = Tile<TileType::Vec, int32_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
          // pto: %11
          uint64_t v193 = (uint64_t) v40;
          TASSIGN(v192, v193);
          // pto: %12
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v194 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
          // pto: %12
          uint64_t v195 = (uint64_t) v40;
          TASSIGN(v194, v195);
          pipe_barrier(PIPE_V);
          TCVT(v194, v192, v18, v17);
          // pto: %13
          Tile<TileType::Vec, int32_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v196 = Tile<TileType::Vec, int32_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
          // pto: %13
          uint64_t v197 = (uint64_t) v39;
          TASSIGN(v196, v197);
          // pto: %14
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v198 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
          // pto: %14
          uint64_t v199 = (uint64_t) v39;
          TASSIGN(v198, v199);
          TCVT(v198, v196, v18, v17);
          // pto: %16
          Tile<TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v200 = Tile<TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
          // pto: %16
          uint64_t v201 = (uint64_t) v38;
          TASSIGN(v200, v201);
          // pto: %17
          Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v202 = Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
          // pto: %17
          uint64_t v203 = (uint64_t) v37;
          TASSIGN(v202, v203);
          // pto: %18
          Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v204 = Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
          // pto: %18
          uint64_t v205 = (uint64_t) v36;
          TASSIGN(v204, v205);
          // pto: %19
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v206 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
          // pto: %19
          uint64_t v207 = (uint64_t) v40;
          TASSIGN(v206, v207);
          pipe_barrier(PIPE_V);
          TROWEXPANDMUL(v206, v194, v200);
          // pto: %20
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v208 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
          // pto: %20
          uint64_t v209 = (uint64_t) v40;
          TASSIGN(v208, v209);
          pipe_barrier(PIPE_V);
          TCOLEXPANDMUL(v208, v206, v202);
          // pto: %21
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v210 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
          // pto: %21
          uint64_t v211 = (uint64_t) v39;
          TASSIGN(v210, v211);
          TROWEXPANDMUL(v210, v198, v200);
          // pto: %22
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v212 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
          // pto: %22
          uint64_t v213 = (uint64_t) v39;
          TASSIGN(v212, v213);
          pipe_barrier(PIPE_V);
          TCOLEXPANDMUL(v212, v210, v204);
          // pto: %23
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v214 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
          // pto: %23
          uint64_t v215 = (uint64_t) v37;
          TASSIGN(v214, v215);
          TNEG(v214, v208);
          // pto: %24
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v216 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
          // pto: %24
          uint64_t v217 = (uint64_t) v37;
          TASSIGN(v216, v217);
          pipe_barrier(PIPE_V);
          TEXP(v216, v214);
          // pto: %25
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v218 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
          // pto: %25
          uint64_t v219 = (uint64_t) v37;
          TASSIGN(v218, v219);
          pipe_barrier(PIPE_V);
          TADDS(v218, v216, v21);
          // pto: %26
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v220 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
          // pto: %26
          uint64_t v221 = (uint64_t) v36;
          TASSIGN(v220, v221);
          pipe_barrier(PIPE_V);
          TRECIP(v220, v218);
          // pto: %27
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v222 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
          // pto: %27
          uint64_t v223 = (uint64_t) v40;
          TASSIGN(v222, v223);
          pipe_barrier(PIPE_V);
          TMUL(v222, v208, v220);
          // pto: %28
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v224 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
          // pto: %28
          uint64_t v225 = (uint64_t) v40;
          TASSIGN(v224, v225);
          pipe_barrier(PIPE_V);
          TMUL(v224, v222, v212);
          v224.SetValidShape(v40, v40);
          // pto: %30
          Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null> v226 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null>(v40, v40);
          // pto: %30
          uint64_t v227 = (uint64_t) v40;
          TASSIGN(v226, v227);
          pipe_barrier(PIPE_V);
          TFILLPAD(v226, v224);
          // pto: %31
          Tile<TileType::Vec, bfloat16_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null> v228 = Tile<TileType::Vec, bfloat16_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null>(v40, v40);
          // pto: %31
          uint64_t v229 = (uint64_t) v40;
          TASSIGN(v228, v229);
          pipe_barrier(PIPE_V);
          TCVT(v228, v226, v16, v17);
        }
      }
    }
    // PYPTO-LIB-AUTHORITY: cross-core-h-bf16-publish begin
    // Keep the non-producing AIV lane on the same publish/acquire generation
    // as the lane that materializes h_bf16.
    pipe_barrier(PIPE_ALL);
    dcci(static_cast<__gm__ void *>(0), ENTIRE_DATA_CACHE);
    dsb(DSB_DDR);
    SYNCALL<SyncCoreType::Mix>();
    dcci(static_cast<__gm__ void *>(0), ENTIRE_DATA_CACHE);
    dsb(DSB_DDR);
    // PYPTO-LIB-AUTHORITY: cross-core-h-bf16-publish end
    for (int64_t i230 = v183; i230 < v186; i230 += v28) {
      // pto: %126, %125
      int32_t v231 = v1[(int64_t) ((uint64_t) i230 + (uint64_t) v26)];
      // pto: %127, %128
      int32_t v232 = v3[(int64_t) v231];
      // pto: %129, %130, %131
      for (int64_t j233 = v40; j233 < ((int64_t) ((uint64_t) ((int64_t) v232) + (uint64_t) v25) / v24); j233 += v34) {
        for (int64_t k234 = v40; k234 < v26; k234 += v34) {
          // pto: %32
          Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v235 = Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
          // pto: %32
          uint64_t v236 = (uint64_t) v37;
          TASSIGN(v235, v236);
          pipe_barrier(PIPE_V);
          TEXPANDS(v235, v20);
          for (int64_t l237 = v40; l237 < v29; l237 += v34) {
            // pto: %33
            Tile<TileType::Vec, bfloat16_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v238 = Tile<TileType::Vec, bfloat16_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
            // pto: %33
            uint64_t v239 = (uint64_t) v39;
            TASSIGN(v238, v239);
            // pto: %34
            Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v240 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
            // pto: %34
            uint64_t v241 = (uint64_t) v40;
            TASSIGN(v240, v241);
            pipe_barrier(PIPE_V);
            TCVT(v240, v238, v16, v17);
            // pto: %35
            Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v242 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
            // pto: %35
            uint64_t v243 = (uint64_t) v39;
            TASSIGN(v242, v243);
            pipe_barrier(PIPE_V);
            TNEG(v242, v240);
            // pto: %36
            Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v244 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
            // pto: %36
            uint64_t v245 = (uint64_t) v40;
            TASSIGN(v244, v245);
            pipe_barrier(PIPE_V);
            TMAX(v244, v240, v242);
            // pto: %37
            Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v246 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
            // pto: %37
            uint64_t v247 = (uint64_t) v39;
            TASSIGN(v246, v247);
            // pto: %38
            Tile<TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v248 = Tile<TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
            // pto: %38
            uint64_t v249 = (uint64_t) v35;
            TASSIGN(v248, v249);
            pipe_barrier(PIPE_V);
            TROWMAX(v248, v244, v246);
            // pto: %39
            Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v250 = Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
            // pto: %39
            uint64_t v251 = (uint64_t) v35;
            TASSIGN(v250, v251);
            // pto: %40
            Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v252 = Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
            // pto: %40
            uint64_t v253 = (uint64_t) v37;
            TASSIGN(v252, v253);
            pipe_barrier(PIPE_V);
            TMAX(v252, v235, v250);
          }
          // pto: %41
          Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v254 = Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
          // pto: %41
          uint64_t v255 = (uint64_t) v40;
          TASSIGN(v254, v255);
          pipe_barrier(PIPE_V);
          TRECIP(v254, v235);
          // pto: %42
          Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v256 = Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
          // pto: %42
          uint64_t v257 = (uint64_t) v39;
          TASSIGN(v256, v257);
          TEXPANDS(v256, v19);
          // pto: %43
          Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v258 = Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
          // pto: %43
          uint64_t v259 = (uint64_t) v37;
          TASSIGN(v258, v259);
          pipe_barrier(PIPE_V);
          TMUL(v258, v254, v256);
          // pto: %44
          Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v260 = Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
          // pto: %44
          uint64_t v261 = (uint64_t) v40;
          TASSIGN(v260, v261);
          pipe_barrier(PIPE_V);
          TRECIP(v260, v258);
          // pto: %47
          Tile<TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v262 = Tile<TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
          // pto: %47
          uint64_t v263 = (uint64_t) v37;
          TASSIGN(v262, v263);
          for (int64_t l264 = v40; l264 < v29; l264 += v34) {
            // pto: %48
            Tile<TileType::Vec, bfloat16_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v265 = Tile<TileType::Vec, bfloat16_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
            // pto: %48
            uint64_t v266 = (uint64_t) v39;
            TASSIGN(v265, v266);
            // pto: %49
            Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v267 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
            // pto: %49
            uint64_t v268 = (uint64_t) v40;
            TASSIGN(v267, v268);
            pipe_barrier(PIPE_V);
            TCVT(v267, v265, v16, v17);
            // pto: %50
            Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v269 = Tile<TileType::Vec, float, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
            // pto: %50
            uint64_t v270 = (uint64_t) v40;
            TASSIGN(v269, v270);
            pipe_barrier(PIPE_V);
            TROWEXPANDMUL(v269, v267, v262);
            // pto: %51
            Tile<TileType::Vec, int32_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v271 = Tile<TileType::Vec, int32_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
            // pto: %51
            uint64_t v272 = (uint64_t) v40;
            TASSIGN(v271, v272);
            pipe_barrier(PIPE_V);
            TCVT(v271, v269, v15, v17);
            // pto: %52
            Tile<TileType::Vec, half, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v273 = Tile<TileType::Vec, half, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
            // pto: %52
            uint64_t v274 = (uint64_t) v40;
            TASSIGN(v273, v274);
            pipe_barrier(PIPE_V);
            TCVT(v273, v271, v16, v17);
            // pto: %53
            Tile<TileType::Vec, int8_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v275 = Tile<TileType::Vec, int8_t, 8, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v40, v40);
            // pto: %53
            uint64_t v276 = (uint64_t) v40;
            TASSIGN(v275, v276);
            pipe_barrier(PIPE_V);
            TCVT(v275, v273, v14, v17);
          }
        }
      }
    }
  }
  wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID1);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID3);
  wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID3);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
#if !defined(__CPU_SIM)
    // Read A2A3 mixed-task subblock id from runtime dispatch context
    pypto_runtime_subblock_id = get_sub_block_id(args);
#endif

    // Read logical SPMD block identity from runtime dispatch payload
    int32_t __pypto_spmd_block_idx = get_block_idx(args);
    int32_t __pypto_spmd_block_num = get_block_num(args);

    // Read SPMD subblock (AIV lane) id from runtime dispatch payload
    int32_t __pypto_spmd_subblock_idx = get_sub_block_id(args);

    // Unpack tensor: local_route_count__ssa_v0
    __gm__ PyPTORuntimeTensor* local_route_count__ssa_v0_tensor = reinterpret_cast<__gm__ PyPTORuntimeTensor*>(args[0]);
    __gm__ int32_t* local_route_count__ssa_v0 = reinterpret_cast<__gm__ int32_t*>(local_route_count__ssa_v0_tensor->buffer.addr) + local_route_count__ssa_v0_tensor->start_offset;

    // Unpack tensor: gate_up_i32_inline575__ssa_v0
    __gm__ PyPTORuntimeTensor* gate_up_i32_inline575__ssa_v0_tensor = reinterpret_cast<__gm__ PyPTORuntimeTensor*>(args[1]);
    __gm__ int32_t* gate_up_i32_inline575__ssa_v0 = reinterpret_cast<__gm__ int32_t*>(gate_up_i32_inline575__ssa_v0_tensor->buffer.addr) + gate_up_i32_inline575__ssa_v0_tensor->start_offset;

    // Unpack tensor: local_expert_count__ssa_v1
    __gm__ PyPTORuntimeTensor* local_expert_count__ssa_v1_tensor = reinterpret_cast<__gm__ PyPTORuntimeTensor*>(args[2]);
    __gm__ int32_t* local_expert_count__ssa_v1 = reinterpret_cast<__gm__ int32_t*>(local_expert_count__ssa_v1_tensor->buffer.addr) + local_expert_count__ssa_v1_tensor->start_offset;

    // Unpack tensor: local_routed_x__ssa_v8
    __gm__ PyPTORuntimeTensor* local_routed_x__ssa_v8_tensor = reinterpret_cast<__gm__ PyPTORuntimeTensor*>(args[3]);
    __gm__ int8_t* local_routed_x__ssa_v8 = reinterpret_cast<__gm__ int8_t*>(local_routed_x__ssa_v8_tensor->buffer.addr) + local_routed_x__ssa_v8_tensor->start_offset;

    // Unpack tensor: w13_2d_inline549__ssa_v0
    __gm__ PyPTORuntimeTensor* w13_2d_inline549__ssa_v0_tensor = reinterpret_cast<__gm__ PyPTORuntimeTensor*>(args[4]);
    __gm__ int8_t* w13_2d_inline549__ssa_v0 = reinterpret_cast<__gm__ int8_t*>(w13_2d_inline549__ssa_v0_tensor->buffer.addr) + w13_2d_inline549__ssa_v0_tensor->start_offset;

    // Unpack tensor: h_bf16_inline547__ssa_v0
    __gm__ PyPTORuntimeTensor* h_bf16_inline547__ssa_v0_tensor = reinterpret_cast<__gm__ PyPTORuntimeTensor*>(args[5]);
    __gm__ bfloat16_t* h_bf16_inline547__ssa_v0 = reinterpret_cast<__gm__ bfloat16_t*>(h_bf16_inline547__ssa_v0_tensor->buffer.addr) + h_bf16_inline547__ssa_v0_tensor->start_offset;

    // Unpack tensor: local_routed_x_scale__ssa_v1
    __gm__ PyPTORuntimeTensor* local_routed_x_scale__ssa_v1_tensor = reinterpret_cast<__gm__ PyPTORuntimeTensor*>(args[6]);
    __gm__ float* local_routed_x_scale__ssa_v1 = reinterpret_cast<__gm__ float*>(local_routed_x_scale__ssa_v1_tensor->buffer.addr) + local_routed_x_scale__ssa_v1_tensor->start_offset;

    // Unpack tensor: w13_r_scale__ssa_v0
    __gm__ PyPTORuntimeTensor* w13_r_scale__ssa_v0_tensor = reinterpret_cast<__gm__ PyPTORuntimeTensor*>(args[7]);
    __gm__ float* w13_r_scale__ssa_v0 = reinterpret_cast<__gm__ float*>(w13_r_scale__ssa_v0_tensor->buffer.addr) + w13_r_scale__ssa_v0_tensor->start_offset;

    // Unpack tensor: h_i8_inline553__ssa_v0
    __gm__ PyPTORuntimeTensor* h_i8_inline553__ssa_v0_tensor = reinterpret_cast<__gm__ PyPTORuntimeTensor*>(args[8]);
    __gm__ int8_t* h_i8_inline553__ssa_v0 = reinterpret_cast<__gm__ int8_t*>(h_i8_inline553__ssa_v0_tensor->buffer.addr) + h_i8_inline553__ssa_v0_tensor->start_offset;

    // Unpack tensor: h_scale_dq_all_inline598__ssa_v0
    __gm__ PyPTORuntimeTensor* h_scale_dq_all_inline598__ssa_v0_tensor = reinterpret_cast<__gm__ PyPTORuntimeTensor*>(args[9]);
    __gm__ float* h_scale_dq_all_inline598__ssa_v0 = reinterpret_cast<__gm__ float*>(h_scale_dq_all_inline598__ssa_v0_tensor->buffer.addr) + h_scale_dq_all_inline598__ssa_v0_tensor->start_offset;

    // Forward to ptoas-generated function
    routed_gmm1_swiglu_quant_aiv(local_route_count__ssa_v0, gate_up_i32_inline575__ssa_v0, local_expert_count__ssa_v1, local_routed_x__ssa_v8, w13_2d_inline549__ssa_v0, h_bf16_inline547__ssa_v0, local_routed_x_scale__ssa_v1, w13_r_scale__ssa_v0, h_i8_inline553__ssa_v0, h_scale_dq_all_inline598__ssa_v0, __pypto_spmd_block_idx, __pypto_spmd_block_num, __pypto_spmd_subblock_idx);
}
