#!/usr/bin/env python3
"""Create a sitecustomize.py that auto-installs the Step3p5 PyPTO vLLM patch.

Use this to launch vLLM without editing vLLM source:

    python tools/step3p5/make_vllm_sitecustomize.py --out-dir /tmp/pypto_patch
    PYTHONPATH=/tmp/pypto_patch:/path/to/pypto-lib \
      PYPTO_STEP3P5_PATCH_MODE=tail \
      vllm serve ...

Every Python process (including vLLM worker subprocesses) imports
``sitecustomize`` during startup, so the patch is installed before Step3p5 model
classes are instantiated.
"""
from __future__ import annotations

import argparse
from pathlib import Path


SITE_TEMPLATE = r'''
# Auto-generated by tools/step3p5/make_vllm_sitecustomize.py.
from __future__ import annotations
import os
import sys
from pathlib import Path

_REPO_ROOT = os.environ.get("PYPTO_LIB_REPO_ROOT", __REPO_ROOT_REPR__)
if _REPO_ROOT and _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

if os.environ.get("PYPTO_STEP3P5_AUTO_PATCH", "1").lower() not in {"0", "false", "no", "off"}:
    try:
        from tools.step3p5.vllm_monkey_patch import install
        install(os.environ.get("PYPTO_STEP3P5_PATCH_MODE", __MODE_REPR__))
    except ModuleNotFoundError:
        # vLLM may not be importable in non-serving helper processes.  Keep
        # startup fail-open unless explicitly requested.
        if os.environ.get("PYPTO_STEP3P5_PATCH_STRICT", "0").lower() in {"1", "true", "yes"}:
            raise
    except Exception:
        if os.environ.get("PYPTO_STEP3P5_PATCH_STRICT", "1").lower() not in {"0", "false", "no", "off"}:
            raise
'''.lstrip()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", required=True)
    parser.add_argument("--repo-root", default=str(Path(__file__).resolve().parents[2]))
    parser.add_argument("--mode", choices=["tail", "shadow", "full"], default="tail")
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "sitecustomize.py"
    path.write_text(SITE_TEMPLATE.replace("__REPO_ROOT_REPR__", repr(args.repo_root)).replace("__MODE_REPR__", repr(args.mode)), encoding="utf-8")
    print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
